markdown:         redcarpet
pygments:         true
paginate:         10

title:            BeginMan的博客
url:              http://beginman.github.io
feed:             /atom.xml
author:
    name:         BeginMan
    email:        pythonsuper@gmail.com
    description:  "The one theme is another web theme design by PIZn."

about:            "中文名：方朋，英文名:BeginMan.一个编程爱好者，也是一个极具想法和折腾的人，现在是一名初级的Pythoner。生活在郑州。搞这个博客的理由就是不要给自己懒惰的借口，要记录和总结一些东西，不论是技术方面还是书评/影评或者生活方面，只要觉得有意义的事情都会记录上去。如果你觉得这篇博客还有点意思，你可以通过下面几种方式联系我，或者到http://www.cnblogs.com/BeginMan/ 关注我之前的博客。"
follow:
    email:        pythonsuper@gmail.com
    github:       https://github.com/BeginMan
    twitter:      http://www.twitter.com/BeginMan
    facebook:     http://facebook.com/BeginMan
description:      Laern more

indexContent:     true
imageLink:        http://images.cnblogs.com/cnblogs_com/BeginMan/548700/o_my.jpg


style:            /css/style.css
blogName:         BeginMan
blogDesc:         A pythoner love IT and life.
favicon:          /favicon.ico
theme:            default

disqus:           BeginMan

copyright:        Copyleft © 2014 BeginMan All rights reserved.
test:             ok
