permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: BeginMan
  email: xinxinyu2011@163.com
  link: http://beginman.cn
  weibo: http://weibo.com/BeginMan
  github: http://github.com/BeginMan

# 站点信息
title: BeginMan的博客 
description: BeginMan的博客
url: http://beginman.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.jpg
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置
ga:
  id: 48054180
  url: beginman.cn

# disqus 设置
disqus:
  shortname: BeginMan

# 主题设置，自动激活某个标签
active: python

# 首页除了最新文章外显示分类
cates: 
  - Linux
  - 思考


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
